package com.go4o.lite.ui.strings

import com.go4o.lite.data.model.Language

data class AppStrings(
    // Tab labels
    val tabHome: String,
    val tabCourses: String,
    val tabReadouts: String,
    val tabSettings: String,

    // Station / Home
    val appTitle: String,
    val station: String,
    val statusConnected: String,
    val statusDisconnected: String,
    val statusStarting: String,
    val statusReady: String,
    val statusReadingCard: String,
    val statusReadError: String,
    val statusFatalError: String,
    val connectStation: String,
    val disconnect: String,
    val dismiss: String,
    val clearAllData: String,
    val clearAllDialogTitle: String,
    val clearAllDialogText: String,
    val clearAllConfirm: String,
    val cancel: String,

    // Courses tab
    val coursesHeading: String,
    val importCourses: String,
    val coursesEmpty: String,
    val courseCount: (Int) -> String,
    val controlsInfo: (Int) -> String,

    // Readouts tab
    val readoutsHeading: String,
    val readoutsEmpty: String,
    val readoutCount: (Int) -> String,
    val clearAll: String,

    // Result status
    val statusPass: String,
    val statusMispunch: String,
    val statusNoCourse: String,

    // Readout detail labels
    val cardSeries: String,
    val course: String,
    val time: String,
    val punches: String,
    val missingControls: String,
    val punchLog: String,
    val collapse: String,
    val expand: String,

    // Overlay
    val cardLabel: (String) -> String,
    val missingLabel: (String) -> String,
    val tapToDismiss: String,

    // Settings
    val settingsHeading: String,
    val overlayDuration: String,
    val seconds: (Int) -> String,
    val overlayStyle: String,
    val styleText: String,
    val styleSmiley: String,
    val previewOverlay: String,
    val previewSuccess: String,
    val previewFail: String,
    val language: String,
    val keepScreenOn: String,
    val smileyPassEmoji: String,
    val smileyFailEmoji: String,

    // Course editing
    val editCourse: String,
    val deleteCourse: String,
    val deleteControl: String,
    val addControl: String,
    val controlNumber: String,
    val save: String,
    val deleteCourseDialogTitle: String,
    val deleteCourseDialogText: String,

    // Errors
    val noCoursesFoundInFile: String,
    val importFailed: (String) -> String
)

fun stringsFor(language: Language): AppStrings = when (language) {
    Language.EN -> englishStrings
    Language.DE -> germanStrings
    Language.FR -> frenchStrings
    Language.NL -> dutchStrings
    Language.ES -> spanishStrings
    Language.IT -> italianStrings
    Language.CS -> czechStrings
}

private val englishStrings = AppStrings(
    tabHome = "Home",
    tabCourses = "Courses",
    tabReadouts = "Readouts",
    tabSettings = "Settings",
    appTitle = "Go4O Lite",
    station = "Station",
    statusConnected = "Connected",
    statusDisconnected = "Disconnected",
    statusStarting = "Starting...",
    statusReady = "Ready",
    statusReadingCard = "Reading card...",
    statusReadError = "Read error",
    statusFatalError = "Fatal error",
    connectStation = "Connect Station",
    disconnect = "Disconnect",
    dismiss = "Dismiss",
    clearAllData = "Clear All Data",
    clearAllDialogTitle = "Clear All Data",
    clearAllDialogText = "This will delete all courses and readouts. This cannot be undone.",
    clearAllConfirm = "Clear All",
    cancel = "Cancel",
    coursesHeading = "Courses",
    importCourses = "Import Courses (IOF XML)",
    coursesEmpty = "No courses loaded.\nImport an IOF XML file to get started.",
    courseCount = { n -> "$n course(s)" },
    controlsInfo = { n -> "$n controls" },
    readoutsHeading = "Readouts",
    readoutsEmpty = "No cards read yet.\nConnect a station and dip a card.",
    readoutCount = { n -> "$n readout(s)" },
    clearAll = "Clear all",
    statusPass = "PASS",
    statusMispunch = "MISPUNCH",
    statusNoCourse = "NO COURSE",
    cardSeries = "Card series",
    course = "Course",
    time = "Time",
    punches = "Punches",
    missingControls = "Missing controls",
    punchLog = "Punch log",
    collapse = "Collapse",
    expand = "Expand",
    cardLabel = { n -> "Card: $n" },
    missingLabel = { c -> "Missing: $c" },
    tapToDismiss = "Tap to dismiss",
    settingsHeading = "Settings",
    overlayDuration = "Overlay Duration",
    seconds = { n -> "$n seconds" },
    overlayStyle = "Overlay Style",
    styleText = "Text",
    styleSmiley = "Smiley",
    previewOverlay = "Preview Overlay",
    previewSuccess = "Preview Success",
    previewFail = "Preview Fail",
    language = "Language",
    keepScreenOn = "Keep Screen On",
    smileyPassEmoji = "Pass emoji",
    smileyFailEmoji = "Fail emoji",
    editCourse = "Edit",
    deleteCourse = "Delete",
    deleteControl = "Delete control",
    addControl = "Add control",
    controlNumber = "Control number",
    save = "Save",
    deleteCourseDialogTitle = "Delete course",
    deleteCourseDialogText = "This will permanently delete this course. This cannot be undone.",
    noCoursesFoundInFile = "No courses found in file",
    importFailed = { msg -> "Import failed: $msg" }
)

private val germanStrings = AppStrings(
    tabHome = "Start",
    tabCourses = "Bahnen",
    tabReadouts = "SI-Chips",
    tabSettings = "Einstellungen",
    appTitle = "Go4O Lite",
    station = "Station",
    statusConnected = "Verbunden",
    statusDisconnected = "Getrennt",
    statusStarting = "Starte...",
    statusReady = "Bereit",
    statusReadingCard = "Lese SI-Chip...",
    statusReadError = "Lesefehler",
    statusFatalError = "Schwerer Fehler",
    connectStation = "Station verbinden",
    disconnect = "Trennen",
    dismiss = "Schließen",
    clearAllData = "Alle Daten löschen",
    clearAllDialogTitle = "Alle Daten löschen",
    clearAllDialogText = "Dies löscht alle Bahnen und SI Chips. Dies kann nicht rückgängig gemacht werden.",
    clearAllConfirm = "Alle löschen",
    cancel = "Abbrechen",
    coursesHeading = "Bahnen",
    importCourses = "Bahnen importieren (IOF XML)",
    coursesEmpty = "Keine Bahnen geladen.\nImportiere eine IOF XML-Datei.",
    courseCount = { n -> "$n Bahn(en)" },
    controlsInfo = { n -> "$n Posten" },
    readoutsHeading = "Auslesungen",
    readoutsEmpty = "Noch keine Karten ausgelesen.\nStation verbinden und Karte einstecken.",
    readoutCount = { n -> "$n Auslesung(en)" },
    clearAll = "Alle löschen",
    statusPass = "OK",
    statusMispunch = "FEHLSTEMPEL",
    statusNoCourse = "KEINE BAHN",
    cardSeries = "SI Card Series",
    course = "Bahn",
    time = "Zeit",
    punches = "Stempel",
    missingControls = "Fehlende Posten",
    punchLog = "Stempelprotokoll",
    collapse = "Einklappen",
    expand = "Ausklappen",
    cardLabel = { n -> "SI: $n" },
    missingLabel = { c -> "Fehlend: $c" },
    tapToDismiss = "Zum Schließen tippen",
    settingsHeading = "Einstellungen",
    overlayDuration = "Anzeigedauer Auslesen",
    seconds = { n -> "$n Sekunden" },
    overlayStyle = "Stil Auslesen",
    styleText = "Text",
    styleSmiley = "Emoji",
    previewOverlay = "Vorschau Auslesen",
    previewSuccess = "Vorschau Erfolg",
    previewFail = "Vorschau Fehler",
    language = "Sprache",
    keepScreenOn = "Bildschirm anlassen",
    smileyPassEmoji = "OK-Emoji",
    smileyFailEmoji = "Fehler-Emoji",
    editCourse = "Bearbeiten",
    deleteCourse = "Löschen",
    deleteControl = "Posten löschen",
    addControl = "Posten hinzufügen",
    controlNumber = "Postennummer",
    save = "Speichern",
    deleteCourseDialogTitle = "Bahn löschen",
    deleteCourseDialogText = "Diese Bahn wird unwiderruflich gelöscht.",
    noCoursesFoundInFile = "Keine Bahnen in Datei gefunden",
    importFailed = { msg -> "Import fehlgeschlagen: $msg" }
)

private val frenchStrings = AppStrings(
    tabHome = "Accueil",
    tabCourses = "Circuits",
    tabReadouts = "Lectures",
    tabSettings = "Paramètres",
    appTitle = "Go4O Lite",
    station = "Station",
    statusConnected = "Connecté",
    statusDisconnected = "Déconnecté",
    statusStarting = "Démarrage...",
    statusReady = "Prêt",
    statusReadingCard = "Lecture carte...",
    statusReadError = "Erreur de lecture",
    statusFatalError = "Erreur fatale",
    connectStation = "Connecter la station",
    disconnect = "Déconnecter",
    dismiss = "Fermer",
    clearAllData = "Supprimer toutes les données",
    clearAllDialogTitle = "Supprimer toutes les données",
    clearAllDialogText = "Cela supprimera tous les circuits et lectures. Cette action est irréversible.",
    clearAllConfirm = "Tout supprimer",
    cancel = "Annuler",
    coursesHeading = "Circuits",
    importCourses = "Importer circuits (IOF XML)",
    coursesEmpty = "Aucun circuit chargé.\nImportez un fichier IOF XML.",
    courseCount = { n -> "$n circuit(s)" },
    controlsInfo = { n -> "$n postes" },
    readoutsHeading = "Lectures",
    readoutsEmpty = "Aucune carte lue.\nConnectez une station et insérez une carte.",
    readoutCount = { n -> "$n lecture(s)" },
    clearAll = "Tout supprimer",
    statusPass = "OK",
    statusMispunch = "PM",
    statusNoCourse = "PAS DE CIRCUIT",
    cardSeries = "Série de carte",
    course = "Circuit",
    time = "Temps",
    punches = "Poinçons",
    missingControls = "Postes manquants",
    punchLog = "Journal des poinçons",
    collapse = "Réduire",
    expand = "Développer",
    cardLabel = { n -> "Carte : $n" },
    missingLabel = { c -> "Manquants : $c" },
    tapToDismiss = "Appuyez pour fermer",
    settingsHeading = "Paramètres",
    overlayDuration = "Durée de l'overlay",
    seconds = { n -> "$n secondes" },
    overlayStyle = "Style de l'overlay",
    styleText = "Texte",
    styleSmiley = "Smiley",
    previewOverlay = "Aperçu de l'overlay",
    previewSuccess = "Aperçu succès",
    previewFail = "Aperçu échec",
    language = "Langue",
    keepScreenOn = "Garder l'écran allumé",
    smileyPassEmoji = "Emoji réussite",
    smileyFailEmoji = "Emoji échec",
    editCourse = "Modifier",
    deleteCourse = "Supprimer",
    deleteControl = "Supprimer poste",
    addControl = "Ajouter poste",
    controlNumber = "Numéro de poste",
    save = "Enregistrer",
    deleteCourseDialogTitle = "Supprimer le circuit",
    deleteCourseDialogText = "Ce circuit sera définitivement supprimé.",
    noCoursesFoundInFile = "Aucun circuit trouvé dans le fichier",
    importFailed = { msg -> "Échec de l'import : $msg" }
)

private val dutchStrings = AppStrings(
    tabHome = "Home",
    tabCourses = "Banen",
    tabReadouts = "Uitlezingen",
    tabSettings = "Instellingen",
    appTitle = "Go4O Lite",
    station = "Station",
    statusConnected = "Verbonden",
    statusDisconnected = "Niet verbonden",
    statusStarting = "Starten...",
    statusReady = "Gereed",
    statusReadingCard = "Kaart lezen...",
    statusReadError = "Leesfout",
    statusFatalError = "Fatale fout",
    connectStation = "Station verbinden",
    disconnect = "Verbreken",
    dismiss = "Sluiten",
    clearAllData = "Alle gegevens wissen",
    clearAllDialogTitle = "Alle gegevens wissen",
    clearAllDialogText = "Dit verwijdert alle banen en uitlezingen. Dit kan niet ongedaan worden gemaakt.",
    clearAllConfirm = "Alles wissen",
    cancel = "Annuleren",
    coursesHeading = "Banen",
    importCourses = "Banen importeren (IOF XML)",
    coursesEmpty = "Geen banen geladen.\nImporteer een IOF XML-bestand.",
    courseCount = { n -> "$n ba(a)n(en)" },
    controlsInfo = { n -> "$n posten" },
    readoutsHeading = "Uitlezingen",
    readoutsEmpty = "Nog geen kaarten uitgelezen.\nVerbind een station en steek een kaart in.",
    readoutCount = { n -> "$n uitlezing(en)" },
    clearAll = "Alles wissen",
    statusPass = "OK",
    statusMispunch = "FOUTPONS",
    statusNoCourse = "GEEN BAAN",
    cardSeries = "Kaartserie",
    course = "Baan",
    time = "Tijd",
    punches = "Ponsen",
    missingControls = "Ontbrekende posten",
    punchLog = "Ponslogboek",
    collapse = "Inklappen",
    expand = "Uitklappen",
    cardLabel = { n -> "Kaart: $n" },
    missingLabel = { c -> "Ontbrekend: $c" },
    tapToDismiss = "Tik om te sluiten",
    settingsHeading = "Instellingen",
    overlayDuration = "Overlayduur",
    seconds = { n -> "$n seconden" },
    overlayStyle = "Overlaystijl",
    styleText = "Tekst",
    styleSmiley = "Smiley",
    previewOverlay = "Overlayvoorbeeld",
    previewSuccess = "Voorbeeld succes",
    previewFail = "Voorbeeld fout",
    language = "Taal",
    keepScreenOn = "Scherm aan houden",
    smileyPassEmoji = "OK-emoji",
    smileyFailEmoji = "Fout-emoji",
    editCourse = "Bewerken",
    deleteCourse = "Verwijderen",
    deleteControl = "Post verwijderen",
    addControl = "Post toevoegen",
    controlNumber = "Postnummer",
    save = "Opslaan",
    deleteCourseDialogTitle = "Baan verwijderen",
    deleteCourseDialogText = "Deze baan wordt permanent verwijderd.",
    noCoursesFoundInFile = "Geen banen gevonden in bestand",
    importFailed = { msg -> "Import mislukt: $msg" }
)

private val spanishStrings = AppStrings(
    tabHome = "Inicio",
    tabCourses = "Recorridos",
    tabReadouts = "Lecturas",
    tabSettings = "Ajustes",
    appTitle = "Go4O Lite",
    station = "Estación",
    statusConnected = "Conectado",
    statusDisconnected = "Desconectado",
    statusStarting = "Iniciando...",
    statusReady = "Listo",
    statusReadingCard = "Leyendo tarjeta...",
    statusReadError = "Error de lectura",
    statusFatalError = "Error fatal",
    connectStation = "Conectar estación",
    disconnect = "Desconectar",
    dismiss = "Cerrar",
    clearAllData = "Borrar todos los datos",
    clearAllDialogTitle = "Borrar todos los datos",
    clearAllDialogText = "Esto eliminará todos los recorridos y lecturas. No se puede deshacer.",
    clearAllConfirm = "Borrar todo",
    cancel = "Cancelar",
    coursesHeading = "Recorridos",
    importCourses = "Importar recorridos (IOF XML)",
    coursesEmpty = "No hay recorridos cargados.\nImporta un archivo IOF XML.",
    courseCount = { n -> "$n recorrido(s)" },
    controlsInfo = { n -> "$n controles" },
    readoutsHeading = "Lecturas",
    readoutsEmpty = "Aún no se han leído tarjetas.\nConecta una estación e inserta una tarjeta.",
    readoutCount = { n -> "$n lectura(s)" },
    clearAll = "Borrar todo",
    statusPass = "OK",
    statusMispunch = "FALTA CONTROL",
    statusNoCourse = "SIN RECORRIDO",
    cardSeries = "Serie de tarjeta",
    course = "Recorrido",
    time = "Tiempo",
    punches = "Registros",
    missingControls = "Controles faltantes",
    punchLog = "Registro de fichajes",
    collapse = "Contraer",
    expand = "Expandir",
    cardLabel = { n -> "Tarjeta: $n" },
    missingLabel = { c -> "Faltantes: $c" },
    tapToDismiss = "Toca para cerrar",
    settingsHeading = "Ajustes",
    overlayDuration = "Duración del overlay",
    seconds = { n -> "$n segundos" },
    overlayStyle = "Estilo del overlay",
    styleText = "Texto",
    styleSmiley = "Smiley",
    previewOverlay = "Vista previa del overlay",
    previewSuccess = "Vista previa éxito",
    previewFail = "Vista previa fallo",
    language = "Idioma",
    keepScreenOn = "Mantener pantalla encendida",
    smileyPassEmoji = "Emoji éxito",
    smileyFailEmoji = "Emoji fallo",
    editCourse = "Editar",
    deleteCourse = "Eliminar",
    deleteControl = "Eliminar control",
    addControl = "Añadir control",
    controlNumber = "Número de control",
    save = "Guardar",
    deleteCourseDialogTitle = "Eliminar recorrido",
    deleteCourseDialogText = "Este recorrido se eliminará permanentemente.",
    noCoursesFoundInFile = "No se encontraron recorridos en el archivo",
    importFailed = { msg -> "Error al importar: $msg" }
)

private val italianStrings = AppStrings(
    tabHome = "Home",
    tabCourses = "Percorsi",
    tabReadouts = "Letture",
    tabSettings = "Impostazioni",
    appTitle = "Go4O Lite",
    station = "Stazione",
    statusConnected = "Connesso",
    statusDisconnected = "Disconnesso",
    statusStarting = "Avvio...",
    statusReady = "Pronto",
    statusReadingCard = "Lettura scheda...",
    statusReadError = "Errore di lettura",
    statusFatalError = "Errore fatale",
    connectStation = "Connetti stazione",
    disconnect = "Disconnetti",
    dismiss = "Chiudi",
    clearAllData = "Cancella tutti i dati",
    clearAllDialogTitle = "Cancella tutti i dati",
    clearAllDialogText = "Questo eliminerà tutti i percorsi e le letture. Non può essere annullato.",
    clearAllConfirm = "Cancella tutto",
    cancel = "Annulla",
    coursesHeading = "Percorsi",
    importCourses = "Importa percorsi (IOF XML)",
    coursesEmpty = "Nessun percorso caricato.\nImporta un file IOF XML.",
    courseCount = { n -> "$n percorso/i" },
    controlsInfo = { n -> "$n punti" },
    readoutsHeading = "Letture",
    readoutsEmpty = "Nessuna scheda letta.\nConnetti una stazione e inserisci una scheda.",
    readoutCount = { n -> "$n lettura/e" },
    clearAll = "Cancella tutto",
    statusPass = "OK",
    statusMispunch = "MANCANTE",
    statusNoCourse = "NESSUN PERCORSO",
    cardSeries = "Serie scheda",
    course = "Percorso",
    time = "Tempo",
    punches = "Punzonature",
    missingControls = "Punti mancanti",
    punchLog = "Registro punzonature",
    collapse = "Comprimi",
    expand = "Espandi",
    cardLabel = { n -> "Scheda: $n" },
    missingLabel = { c -> "Mancanti: $c" },
    tapToDismiss = "Tocca per chiudere",
    settingsHeading = "Impostazioni",
    overlayDuration = "Durata overlay",
    seconds = { n -> "$n secondi" },
    overlayStyle = "Stile overlay",
    styleText = "Testo",
    styleSmiley = "Smiley",
    previewOverlay = "Anteprima overlay",
    previewSuccess = "Anteprima successo",
    previewFail = "Anteprima errore",
    language = "Lingua",
    keepScreenOn = "Mantieni schermo acceso",
    smileyPassEmoji = "Emoji successo",
    smileyFailEmoji = "Emoji errore",
    editCourse = "Modifica",
    deleteCourse = "Elimina",
    deleteControl = "Elimina punto",
    addControl = "Aggiungi punto",
    controlNumber = "Numero punto",
    save = "Salva",
    deleteCourseDialogTitle = "Elimina percorso",
    deleteCourseDialogText = "Questo percorso verrà eliminato definitivamente.",
    noCoursesFoundInFile = "Nessun percorso trovato nel file",
    importFailed = { msg -> "Importazione fallita: $msg" }
)

private val czechStrings = AppStrings(
    tabHome = "Úvod",
    tabCourses = "Tratě",
    tabReadouts = "Čtení",
    tabSettings = "Nastavení",
    appTitle = "Go4O Lite",
    station = "Stanice",
    statusConnected = "Připojeno",
    statusDisconnected = "Odpojeno",
    statusStarting = "Spouštění...",
    statusReady = "Připraveno",
    statusReadingCard = "Čtení čipu...",
    statusReadError = "Chyba čtení",
    statusFatalError = "Kritická chyba",
    connectStation = "Připojit stanici",
    disconnect = "Odpojit",
    dismiss = "Zavřít",
    clearAllData = "Smazat všechna data",
    clearAllDialogTitle = "Smazat všechna data",
    clearAllDialogText = "Toto smaže všechny tratě a čtení. Tuto akci nelze vrátit.",
    clearAllConfirm = "Smazat vše",
    cancel = "Zrušit",
    coursesHeading = "Tratě",
    importCourses = "Importovat tratě (IOF XML)",
    coursesEmpty = "Žádné tratě načteny.\nImportujte soubor IOF XML.",
    courseCount = { n -> "$n trať/í" },
    controlsInfo = { n -> "$n kontrol" },
    readoutsHeading = "Čtení",
    readoutsEmpty = "Zatím žádné čipy přečteny.\nPřipojte stanici a vložte čip.",
    readoutCount = { n -> "$n čtení" },
    clearAll = "Smazat vše",
    statusPass = "OK",
    statusMispunch = "CHYBÍ KONTROLA",
    statusNoCourse = "BEZ TRATĚ",
    cardSeries = "Série čipu",
    course = "Trať",
    time = "Čas",
    punches = "Ražení",
    missingControls = "Chybějící kontroly",
    punchLog = "Protokol ražení",
    collapse = "Sbalit",
    expand = "Rozbalit",
    cardLabel = { n -> "Čip: $n" },
    missingLabel = { c -> "Chybí: $c" },
    tapToDismiss = "Klepněte pro zavření",
    settingsHeading = "Nastavení",
    overlayDuration = "Doba zobrazení",
    seconds = { n -> "$n sekund" },
    overlayStyle = "Styl zobrazení",
    styleText = "Text",
    styleSmiley = "Smiley",
    previewOverlay = "Náhled zobrazení",
    previewSuccess = "Náhled úspěch",
    previewFail = "Náhled chyba",
    language = "Jazyk",
    keepScreenOn = "Ponechat obrazovku zapnutou",
    smileyPassEmoji = "Emoji úspěch",
    smileyFailEmoji = "Emoji chyba",
    editCourse = "Upravit",
    deleteCourse = "Smazat",
    deleteControl = "Smazat kontrolu",
    addControl = "Přidat kontrolu",
    controlNumber = "Číslo kontroly",
    save = "Uložit",
    deleteCourseDialogTitle = "Smazat trať",
    deleteCourseDialogText = "Tato trať bude trvale smazána.",
    noCoursesFoundInFile = "V souboru nebyly nalezeny žádné tratě",
    importFailed = { msg -> "Import se nezdařil: $msg" }
)
